### ISSUE TITLE
encapsulate the shield data join gist into moztelemetry

### ISSUE THREAD

**Issue by hamilton** [mozilla/python_moztelemetry#167]
Hello! First time issue filer, long time listener.

Currently, when we run a Shield study that requires joining on the telemetry data, we direct users to [this gist](https://gist.github.com/jtg567/ee6158dca0d2f2018ba0d1bf25a0284e) or something like it (I don't think jgaunt was the originator of that script, maybe it was Frank whom I've never met). It's awesome that SOMEONE has put down the time to at least document the arduous process of joining telemetry data with shield study data, but it's still a very, very painful process to get from nothing to joined data set.

I envision this task becoming more and more important as our surveys get paired with telemetry data for all sorts of things, and so I'd like to submit this gist as a candidate for a new `import join_to_shield from moztelemetry` so that we don't have to go through the terrifying prospect of going step by step.

**Comment by jtg567** [comment]
I want to echo the importance of this to the work we do in S&I and emphasize the huge efficiency boost it would be.

**Comment by maurodoglio** [comment]
@hamilton the gist you linked to contains a etl job as far as I understand. The best place to store that code is imho [python_mozetl](https://github.com/mozilla/python_mozetl). I see there is already [some code](https://github.com/mozilla/python_mozetl/tree/master/mozetl/shield) there that is specific to shield. I would suggest to refactor the code in that notebook so that it can be reused from more than one job and put in it in the shield module. I'm happy to provide some guidance and do the code reviews if needed.
